public void testArrayOutOfBoundsException() throws Exception {
    MiniDFSCluster cluster = null;
    try {
        Configuration conf = new Configuration();
        cluster = new MiniDFSCluster(conf, 2, true, null);
        cluster.waitActive();
        FileSystem fs = cluster.getFileSystem();
        final Path FILE_PATH = new Path("/tmp.txt");
        final long FILE_LEN = 1L;
        DFSTestUtil.createFile(fs, FILE_PATH, FILE_LEN, (short) 2, 1L);
        // get the block
        File dataDir = new File(cluster.getDataDirectory(), "data1/current");
        Block blk = getBlock(dataDir);
        if (blk == null) {
            blk = getBlock(new File(cluster.getDataDirectory(), "dfs/data/data2/current"));
        }
        assertFalse(blk == null);
        // start a third datanode
        cluster.startDataNodes(conf, 1, true, null, null);
        ArrayList<DataNode> datanodes = cluster.getDataNodes();
        assertEquals(datanodes.size(), 3);
        DataNode dataNode = datanodes.get(2);
        // report corrupted block by the third datanode
        cluster.getNameNode().namesystem.markBlockAsCorrupt(blk, new DatanodeInfo(dataNode.dnRegistration));
        // open the file
        fs.open(FILE_PATH);
        // clean up
        fs.delete(FILE_PATH, false);
    } finally {
        if (cluster != null) {
            cluster.shutdown();
        }
    }
}
