public void testPreparedNonRowStatement() {
    try {
        PreparedStatement ps = netConn.prepareStatement("UPDATE nullmix set xtra = ? WHERE i < ?");
        ps.setString(1, "first");
        ps.setInt(2, 25);
        assertEquals("First update failed", 4, ps.executeUpdate());
        ps.setString(1, "second");
        ps.setInt(2, 15);
        assertEquals("Second update failed", 2, ps.executeUpdate());
        ps.close();
        ResultSet rs = netConn.createStatement().executeQuery("SELECT i, 3, vc, xtra FROM nullmix ORDER BY i");
        assertTrue("No rows fetched", rs.next());
        assertEquals("second", rs.getString(4));
        assertEquals(5, rs.getInt(1));
        assertEquals(3, rs.getInt(2));
        assertEquals("five", rs.getString(3));
        assertTrue("No rows fetched", rs.next());
        assertEquals("second", rs.getString(4));
        assertEquals(10, rs.getInt(1));
        assertEquals(3, rs.getInt(2));
        assertEquals("ten", rs.getString(3));
        assertTrue("No rows fetched", rs.next());
        assertEquals("first", rs.getString(4));
        assertEquals(15, rs.getInt(1));
        assertEquals(3, rs.getInt(2));
        assertEquals("fifteen", rs.getString(3));
        assertTrue("Not enough rows fetched", rs.next());
        assertEquals(3, rs.getInt(2));
        assertEquals(21, rs.getInt(1));
        assertEquals("twenty one", rs.getString(3));
        assertEquals("first", rs.getString(4));
        assertTrue("Not enough rows fetched", rs.next());
        assertEquals(3, rs.getInt(2));
        assertEquals(25, rs.getInt(1));
        assertNull(rs.getString(3));
        assertNull(rs.getString(4));
        assertTrue("Not enough rows fetched", rs.next());
        assertEquals(3, rs.getInt(2));
        assertEquals(40, rs.getInt(1));
        assertEquals("forty", rs.getString(3));
        assertNull(rs.getString(4));
        assertFalse("Too many rows fetched", rs.next());
        rs.close();
    } catch (SQLException se) {
        junit.framework.AssertionFailedError ase = new junit.framework.AssertionFailedError(se.getMessage());
        ase.initCause(se);
        throw ase;
    }
}
