public void testAddAndRemoveUser() throws Exception {
    User user = new User("testuser");
    user.setPassword("testpass");
    user.setFirstName("Test");
    user.setLastName("Last");
    Address address = new Address();
    address.setCity("Denver");
    address.setProvince("CO");
    address.setCountry("USA");
    address.setPostalCode("80210");
    user.setAddress(address);
    user.setEmail("timchen.sh@gmail.com");
    user.setWebsite("http://www.sunray.com.cn");
    Role role = rdao.getRoleByName(Constants.USER_ROLE);
    assertNotNull(role.getId());
    user.addRole(role);
    dao.saveUser(user);
    assertNotNull(user.getId());
    assertEquals("testpass", user.getPassword());
    dao.removeUser(user.getId());
    try {
        user = dao.getUser(user.getId());
        fail("getUser didn't throw DataAccessException");
    } catch (DataAccessException d) {
        assertNotNull(d);
    }
}
