void notifyCallback(StepTaskCallback callback, StepTask taskExecuted, ExecutionResult result) throws Exception;
